export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_home_body.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_add_group_body.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_home_widget.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_professor_background.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_add_group_widget.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_group_info_body.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_config_group_body.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_config_group_add_student.dart';
export 'package:Openedu.IA/widgets/custom_professor_widgets/custom_config_group_change_name.dart';
